platform: linux/arm

clone:
  git:
    image: quay.io/armswarm/drone-git

pipeline:
  prepare:
    image: quay.io/armswarm/alpine:3.6
    environment:
      - ALPINE_VERSION=3.6
      - GOLANG_VERSION=1.9.0
      - GOLANG_PACKAGE=1.9-r2
    commands:
      - |-
          sed -i \
            -e "s/{{GOLANG_VERSION}}/$${GOLANG_VERSION}/" \
            -e "s/{{GOLANG_PACKAGE}}/$${GOLANG_PACKAGE}/" \
            -e "s/{{ALPINE_VERSION}}/$${ALPINE_VERSION}/" \
            Dockerfile

  build_and_publish:
    image: quay.io/armswarm/drone-docker
    secrets: [ docker_registry, docker_username, docker_password ]
    repo: quay.io/armswarm/golang
    tag: [ "1.9.0-alpine", "1.9-alpine", "1-alpine", "alpine" ]
    when:
      branch: master
      event: push

  notify:
    image: quay.io/armswarm/drone-slack
    secrets: [ slack_webhook, plugin_channel, plugin_template ]
    when:
      status: [ failure, success ]
